-- =============================================================
-- 최근 본 이벤트 (viewed_events)
-- 사용자가 열람한 이벤트와 마지막 조회 시각을 저장한다.
-- 기록은 get_event 호출 시 upsert 되며, get_viewed_events 로 최근 일주일 내 기록을 조회한다.
-- =============================================================

create table "public"."viewed_events" (
  "id" bigint generated by default as identity not null,
  "user_id" uuid not null,
  "event_id" bigint not null,
  "viewed_at" timestamp without time zone not null default now()  -- 마지막 조회 시각 (재조회 시 갱신)
);


alter table "public"."viewed_events" enable row level security;

-- PK
CREATE UNIQUE INDEX viewed_events_pkey ON public.viewed_events USING btree (id);

alter table "public"."viewed_events" add constraint "viewed_events_pkey" PRIMARY KEY using index "viewed_events_pkey";

-- FK
alter table "public"."viewed_events" add constraint "viewed_events_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) not valid;

alter table "public"."viewed_events" validate constraint "viewed_events_user_id_fkey";

alter table "public"."viewed_events" add constraint "viewed_events_event_id_fkey" FOREIGN KEY (event_id) REFERENCES public.events(id) not valid;

alter table "public"."viewed_events" validate constraint "viewed_events_event_id_fkey";

-- 인덱스
-- (user_id, event_id) 유니크: 사용자별 이벤트당 1행 보장 → get_event 의 upsert ON CONFLICT 대상
-- (선행 컬럼이 user_id 라 user_id 단독 조회도 커버하므로 별도 user_id 인덱스는 두지 않음)
CREATE UNIQUE INDEX viewed_events_user_id_event_id_key
  ON public.viewed_events USING btree (user_id, event_id);

ALTER TABLE "public"."viewed_events"
  ADD CONSTRAINT "viewed_events_user_id_event_id_key"
  UNIQUE USING INDEX "viewed_events_user_id_event_id_key";

-- (user_id, viewed_at DESC): get_viewed_events 의 사용자별 최신순 페이지네이션(필터+정렬) 커버
CREATE INDEX viewed_events_user_id_viewed_at_idx
  ON public.viewed_events USING btree (user_id, viewed_at DESC);

-- 권한: get_event(INVOKER) 가 사용자 컨텍스트에서 INSERT/UPDATE 하므로 insert/update 필요
grant select, insert, update on table "public"."viewed_events" to "authenticated";

grant select, insert, update, delete on table "public"."viewed_events" to "service_role";

grant references on table "public"."viewed_events" to "service_role";

grant trigger on table "public"."viewed_events" to "service_role";

grant truncate on table "public"."viewed_events" to "service_role";


create policy "본인 조회 기록만 조회"
on "public"."viewed_events"
as permissive
for select
to authenticated
using (((SELECT auth.uid()) = user_id));


create policy "본인 id로만 조회 기록 생성"
on "public"."viewed_events"
as permissive
for insert
to authenticated
with check (((SELECT auth.uid()) = user_id));


create policy "본인 조회 기록만 수정"
on "public"."viewed_events"
as permissive
for update
to authenticated
using (((SELECT auth.uid()) = user_id))
with check (((SELECT auth.uid()) = user_id));


-- =============================================================
-- get_event 갱신: 단건 이벤트 조회 시 "최근 본 이벤트" 기록 추가
-- 기존 정의(20260525150000)와 동일하되 아래 두 가지가 변경됨
--   (1) STABLE 제거 → 쓰기(upsert)를 수행하므로 VOLATILE 함수여야 함
--   (2) 함수 말미에 viewed_events upsert 로직 추가
-- =============================================================
CREATE OR REPLACE FUNCTION public.get_event(
  p_event_id bigint
)
RETURNS json
LANGUAGE plpgsql
-- STABLE 제거: viewed_events 에 INSERT/UPDATE 하므로 VOLATILE(기본값) 이어야 함
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  v_event           json;
  v_subscription_id bigint;
  v_is_subscribed   boolean;
BEGIN
  IF auth.uid() IS NOT NULL THEN
    SELECT id INTO v_subscription_id
    FROM public.subscriptions
    WHERE topic_id = (SELECT topic_id FROM public.events WHERE id = p_event_id)
      AND user_id = auth.uid();
    v_is_subscribed := v_subscription_id IS NOT NULL;
  ELSE
    v_subscription_id := NULL;
    v_is_subscribed   := false;
  END IF;

  SELECT row_to_json(e) INTO v_event
  FROM (
    SELECT
      ev.topic_id,
      ev.id               AS event_id,
      t.title             AS topic_title,
      ev.title            AS event_title,
      ev.category,
      ev.summary,
      ev.article_count,
      ev.left_count,
      ev.mid_count,
      ev.right_count,
      ev.abusing_count,
      (
        SELECT jsonb_build_object(
          'left',  COALESCE(array_agg(DISTINCT a.publisher) FILTER (WHERE a.bias_type = '진보'), ARRAY[]::text[]),
          'mid',   COALESCE(array_agg(DISTINCT a.publisher) FILTER (WHERE a.bias_type = '중도'), ARRAY[]::text[]),
          'right', COALESCE(array_agg(DISTINCT a.publisher) FILTER (WHERE a.bias_type = '보수'), ARRAY[]::text[])
        )
        FROM public.event_articles ea
        JOIN public.articles a ON a.id = ea.article_id
        LEFT JOIN public.abusing_articles ab ON ab.article_id = ea.article_id AND ab.event_id = ea.event_id
        WHERE ea.event_id = ev.id
          AND ab.id IS NULL
      )                   AS publishers,
      ev.event_image_url,
      ev.created_at,
      ev.updated_at,
      ev.prev_event_id,
      ev.next_event_id,
      prev_ev.title       AS prev_event_title,
      next_ev.title       AS next_event_title,
      v_subscription_id   AS subscription_id,
      v_is_subscribed     AS is_subscribed
    FROM public.events ev
    LEFT JOIN public.topics t ON t.id = ev.topic_id
    LEFT JOIN public.events prev_ev ON prev_ev.id = ev.prev_event_id
    LEFT JOIN public.events next_ev ON next_ev.id = ev.next_event_id
    WHERE ev.id = p_event_id
  ) e;

  IF v_event IS NULL THEN
    RAISE EXCEPTION '존재하지 않는 이벤트입니다';
  END IF;

  -- ▼▼▼ 추가된 부분: 최근 본 이벤트 기록 (로그인 사용자만) ▼▼▼
  -- 같은 이벤트 재조회 시 새 행을 만들지 않고 viewed_at 만 갱신한다.
  -- anon 호출은 auth.uid() 가 NULL 이므로 기록하지 않는다.
  IF auth.uid() IS NOT NULL THEN
    INSERT INTO public.viewed_events (user_id, event_id)
    VALUES (auth.uid(), p_event_id)
    ON CONFLICT ON CONSTRAINT viewed_events_user_id_event_id_key
    DO UPDATE SET viewed_at = now();
  END IF;
  -- ▲▲▲ 추가된 부분 끝 ▲▲▲

  RETURN v_event;
END;
$$;


-- =======================================================================
-- get_viewed_events: 최근 일주일 내 본인이 조회한 이벤트 목록 (viewed_at DESC)
-- =======================================================================
CREATE OR REPLACE FUNCTION public.get_viewed_events(
  p_page int DEFAULT 1,
  p_size int DEFAULT 9
)
RETURNS json
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  v_total_count int;
  v_total_pages int;
  v_events      json;
BEGIN
  p_page := COALESCE(p_page, 1);
  p_size := COALESCE(p_size, 9);

  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION '로그인이 필요합니다';
  END IF;

  IF p_page < 1 THEN
    RAISE EXCEPTION 'page는 1 이상이어야 합니다';
  END IF;

  IF p_size < 1 THEN
    RAISE EXCEPTION 'size는 1 이상이어야 합니다';
  END IF;
  p_size := LEAST(p_size, 100);

  -- 최근 일주일 범위 내 본인 기록만 집계
  SELECT COUNT(*)
  INTO v_total_count
  FROM public.viewed_events v
  WHERE v.user_id = auth.uid()
    AND v.viewed_at >= now() - interval '7 days';

  v_total_pages := CEIL(v_total_count::numeric / p_size);

  SELECT array_to_json(array_agg(row_to_json(r)))
  INTO v_events
  FROM (
    SELECT
      e.id          AS event_id,
      e.topic_id,
      t.title       AS topic_title,
      e.title       AS event_title,
      e.category,
      e.summary,
      e.created_at,
      e.updated_at,
      v.viewed_at,
      s.id             AS subscription_id,
      s.id IS NOT NULL AS is_subscribed
    FROM public.viewed_events v
    JOIN public.events e ON e.id = v.event_id
    LEFT JOIN public.topics t ON t.id = e.topic_id
    -- 토픽 구독 여부 판정 (구독했으면 subscription_id 존재 → is_subscribed = true)
    LEFT JOIN public.subscriptions s ON s.topic_id = e.topic_id AND s.user_id = auth.uid()
    WHERE v.user_id = auth.uid()
      AND v.viewed_at >= now() - interval '7 days'
    ORDER BY v.viewed_at DESC
    LIMIT  p_size
    OFFSET (p_page - 1) * p_size
  ) r;

  RETURN json_build_object(
    'events',      COALESCE(v_events, '[]'::json),
    'page',        p_page,
    'size',        p_size,
    'total_count', v_total_count,
    'total_pages', v_total_pages
  );
END;
$$;


GRANT EXECUTE ON FUNCTION "public"."get_event"(bigint) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_event"(bigint) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_event"(bigint) TO "service_role";

GRANT EXECUTE ON FUNCTION "public"."get_viewed_events"(int, int) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_viewed_events"(int, int) TO "service_role";
