create table "public"."notifications" (
  "id" bigint generated by default as identity not null,
  "created_at" timestamp without time zone not null default now(),
  "user_id" uuid not null,
  "topic_id" bigint not null,
  "event_id" bigint not null,
  "read_at" timestamp without time zone
);


alter table "public"."notifications" enable row level security;

CREATE UNIQUE INDEX notifications_pkey ON public.notifications USING btree (id);

CREATE UNIQUE INDEX notifications_user_id_event_id_key
  ON public.notifications USING btree (user_id, event_id);

CREATE INDEX notifications_user_id_created_at_idx
  ON public.notifications USING btree (user_id, created_at DESC, id DESC);

CREATE INDEX notifications_user_id_unread_idx
  ON public.notifications USING btree (user_id, created_at DESC, id DESC)
  WHERE read_at IS NULL;

alter table "public"."notifications" add constraint "notifications_pkey" PRIMARY KEY using index "notifications_pkey";

alter table "public"."notifications"
  add constraint "notifications_user_id_event_id_key"
  UNIQUE using index "notifications_user_id_event_id_key";

alter table "public"."notifications" add constraint "notifications_event_id_fkey" FOREIGN KEY (event_id) REFERENCES public.events(id) not valid;

alter table "public"."notifications" validate constraint "notifications_event_id_fkey";

alter table "public"."notifications" add constraint "notifications_topic_id_fkey" FOREIGN KEY (topic_id) REFERENCES public.topics(id) not valid;

alter table "public"."notifications" validate constraint "notifications_topic_id_fkey";

alter table "public"."notifications" add constraint "notifications_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) not valid;

alter table "public"."notifications" validate constraint "notifications_user_id_fkey";

grant select, update, delete on table "public"."notifications" to "authenticated";

grant delete on table "public"."notifications" to "service_role";

grant insert on table "public"."notifications" to "service_role";

grant references on table "public"."notifications" to "service_role";

grant select on table "public"."notifications" to "service_role";

grant trigger on table "public"."notifications" to "service_role";

grant truncate on table "public"."notifications" to "service_role";

grant update on table "public"."notifications" to "service_role";


create policy "본인 알림만 조회"
on "public"."notifications"
as permissive
for select
to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));


create policy "본인 알림만 수정"
on "public"."notifications"
as permissive
for update
to authenticated
using (((SELECT auth.uid()) = user_id))
with check (((SELECT auth.uid()) = user_id));


create policy "본인 알림만 삭제"
on "public"."notifications"
as permissive
for delete
to authenticated
using (((SELECT auth.uid()) = user_id));


CREATE OR REPLACE FUNCTION public.create_notifications_for_new_event()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  INSERT INTO public.notifications (user_id, topic_id, event_id)
  SELECT s.user_id, NEW.topic_id, NEW.id
  FROM public.subscriptions s
  WHERE s.topic_id = NEW.topic_id
  ON CONFLICT ON CONSTRAINT notifications_user_id_event_id_key DO NOTHING;

  RETURN NEW;
END;
$$;


CREATE TRIGGER create_notifications_after_event_insert
AFTER INSERT ON public.events
FOR EACH ROW
EXECUTE FUNCTION public.create_notifications_for_new_event();


CREATE OR REPLACE FUNCTION public.get_notifications(
  p_page int DEFAULT 1,
  p_size int DEFAULT 20
)
RETURNS json
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  v_page int := coalesce(p_page, 1);
  v_size int := coalesce(p_size, 20);
  v_offset int;
  v_notifications json;
  v_total_count int;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION '로그인이 필요합니다.';
  END IF;

  IF v_page < 1 THEN
    RAISE EXCEPTION '페이지는 1 이상이어야 합니다.';
  END IF;

  IF v_size < 1 THEN
    RAISE EXCEPTION '페이지 크기는 1 이상이어야 합니다.';
  END IF;

  IF v_size > 100 THEN
    v_size := 100;
  END IF;

  v_offset := (v_page - 1) * v_size;

  SELECT count(*)
  INTO v_total_count
  FROM public.notifications n
  WHERE n.user_id = auth.uid();

  SELECT coalesce(
    json_agg(row_to_json(result) ORDER BY result.created_at DESC, result.id DESC),
    '[]'::json
  )
  INTO v_notifications
  FROM (
    SELECT
      n.id,
      n.created_at,
      n.read_at,
      (n.read_at IS NOT NULL) AS is_read,
      n.topic_id,
      t.category AS topic_category,
      t.title AS topic_title,
      n.event_id,
      e.title AS event_title,
      e.summary AS event_summary,
      e.event_image_url
    FROM public.notifications n
    JOIN public.topics t ON t.id = n.topic_id
    JOIN public.events e ON e.id = n.event_id
    WHERE n.user_id = auth.uid()
    ORDER BY n.created_at DESC, n.id DESC
    LIMIT v_size OFFSET v_offset
  ) result;

  RETURN json_build_object(
    'notifications', v_notifications,
    'page', v_page,
    'size', v_size,
    'total_count', v_total_count,
    'total_pages', ceil(v_total_count::numeric / v_size)::int
  );
END;
$$;


CREATE OR REPLACE FUNCTION public.get_unread_notification_count()
RETURNS json
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  v_unread_count int;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION '로그인이 필요합니다.';
  END IF;

  SELECT count(*)
  INTO v_unread_count
  FROM public.notifications n
  WHERE n.user_id = auth.uid()
    AND n.read_at IS NULL;

  RETURN json_build_object('unread_count', v_unread_count);
END;
$$;


CREATE OR REPLACE FUNCTION public.mark_notification_as_read(
  p_notification_id bigint
)
RETURNS json
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  v_notification public.notifications%ROWTYPE;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION '로그인이 필요합니다.';
  END IF;

  IF p_notification_id IS NULL THEN
    RAISE EXCEPTION '알림 ID가 필요합니다.';
  END IF;

  UPDATE public.notifications n
  SET read_at = coalesce(n.read_at, now())
  WHERE n.id = p_notification_id
    AND n.user_id = auth.uid()
  RETURNING n.* INTO v_notification;

  IF v_notification.id IS NULL THEN
    RAISE EXCEPTION '존재하지 않는 알림입니다.';
  END IF;

  RETURN json_build_object(
    'notification_id', v_notification.id,
    'read_at', v_notification.read_at
  );
END;
$$;


CREATE OR REPLACE FUNCTION public.mark_all_notifications_as_read()
RETURNS json
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  v_updated_count int;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION '로그인이 필요합니다.';
  END IF;

  UPDATE public.notifications n
  SET read_at = now()
  WHERE n.user_id = auth.uid()
    AND n.read_at IS NULL;

  GET DIAGNOSTICS v_updated_count = ROW_COUNT;

  RETURN json_build_object('updated_count', v_updated_count);
END;
$$;


CREATE OR REPLACE FUNCTION public.delete_notification(
  p_notification_id bigint
)
RETURNS void
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION '로그인이 필요합니다.';
  END IF;

  IF p_notification_id IS NULL THEN
    RAISE EXCEPTION '알림 ID가 필요합니다.';
  END IF;

  DELETE FROM public.notifications n
  WHERE n.id = p_notification_id
    AND n.user_id = auth.uid();
END;
$$;


CREATE OR REPLACE FUNCTION public.delete_all_notifications()
RETURNS json
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  v_deleted_count int;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION '로그인이 필요합니다.';
  END IF;

  DELETE FROM public.notifications n
  WHERE n.user_id = auth.uid();

  GET DIAGNOSTICS v_deleted_count = ROW_COUNT;

  RETURN json_build_object('deleted_count', v_deleted_count);
END;
$$;


GRANT EXECUTE ON FUNCTION public.create_notifications_for_new_event() TO service_role;
GRANT EXECUTE ON FUNCTION public.get_notifications(int, int) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_unread_notification_count() TO authenticated;
GRANT EXECUTE ON FUNCTION public.mark_notification_as_read(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.mark_all_notifications_as_read() TO authenticated;
GRANT EXECUTE ON FUNCTION public.delete_notification(bigint) TO authenticated;
GRANT EXECUTE ON FUNCTION public.delete_all_notifications() TO authenticated;
