create extension if not exists vector;

-- 기사 (제목 + 첫 문단) 임베딩
alter table articles
  add column embedding vector(768);

-- 이벤트 (제목 + 요약문) 임베딩
alter table events
  add column embedding vector(768);

-- 토픽 분류 전 이벤트 허용: (article_count - abusing_count) >= n 조건으로 서버에서 판단
alter table events
  alter column topic_id drop not null;

-- 토픽별 원인 문장 및 임베딩 저장
create table topic_causes (
  id              bigint generated by default as identity primary key,
  topic_id        bigint not null references topics(id),
  cause_text      text not null,
  cause_embedding vector(768)
);

alter table topic_causes enable row level security;

grant select, insert, update, delete on table topic_causes to service_role;
