create type "public"."abusing_type" as enum ('title_content_mismatch', 'content_context_mismatch');


create table "public"."abusing_articles" (
  "id" bigint generated by default as identity not null,
  "event_id" bigint not null,
  "article_id" bigint not null,
  "type" public.abusing_type not null
);


alter table "public"."abusing_articles" enable row level security;

CREATE UNIQUE INDEX abusing_articles_pkey ON public.abusing_articles USING btree (id);

alter table "public"."abusing_articles" add constraint "abusing_articles_pkey" PRIMARY KEY using index "abusing_articles_pkey";

alter table "public"."abusing_articles" add constraint "abusing_articles_article_id_fkey" FOREIGN KEY (article_id) REFERENCES public.articles(id) not valid;

alter table "public"."abusing_articles" validate constraint "abusing_articles_article_id_fkey";

alter table "public"."abusing_articles" add constraint "abusing_articles_event_id_fkey" FOREIGN KEY (event_id) REFERENCES public.events(id) not valid;

alter table "public"."abusing_articles" validate constraint "abusing_articles_event_id_fkey";


grant select on table "public"."abusing_articles" to "anon";

grant select on table "public"."abusing_articles" to "authenticated";

grant select, insert, update, delete on table "public"."abusing_articles" to "service_role";

grant references on table "public"."abusing_articles" to "service_role";

grant trigger on table "public"."abusing_articles" to "service_role";

grant truncate on table "public"."abusing_articles" to "service_role";


create policy "Enable read access for all users"
on "public"."abusing_articles"
as permissive
for select
to anon, authenticated
using (true);


CREATE OR REPLACE FUNCTION public.increment_abusing_count()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  UPDATE public.events
  SET abusing_count = abusing_count + 1
  WHERE id = NEW.event_id;

  RAISE LOG 'increment_abusing_count: event_id=%, article_id=%, type=%',
    NEW.event_id, NEW.article_id, NEW.type;

  RETURN NEW;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.increment_abusing_count() FROM PUBLIC;

CREATE TRIGGER increment_abusing_count
AFTER INSERT ON public.abusing_articles
FOR EACH ROW EXECUTE FUNCTION public.increment_abusing_count();


CREATE OR REPLACE FUNCTION public.decrement_bias_count()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_bias_type public.bias_type;
BEGIN
  SELECT bias_type INTO v_bias_type
  FROM public.articles
  WHERE id = NEW.article_id;

  UPDATE public.events
  SET
    left_count  = CASE WHEN v_bias_type = 'left'  THEN left_count  - 1 ELSE left_count  END,
    mid_count   = CASE WHEN v_bias_type = 'mid'   THEN mid_count   - 1 ELSE mid_count   END,
    right_count = CASE WHEN v_bias_type = 'right' THEN right_count - 1 ELSE right_count END
  WHERE id = NEW.event_id;

  RAISE LOG 'decrement_bias_count: event_id=%, article_id=%, bias_type=%',
    NEW.event_id, NEW.article_id, v_bias_type;

  RETURN NEW;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.decrement_bias_count() FROM PUBLIC;

CREATE TRIGGER decrement_bias_count
AFTER INSERT ON public.abusing_articles
FOR EACH ROW EXECUTE FUNCTION public.decrement_bias_count();



