create table "public"."event_articles" (
  "id" bigint generated by default as identity not null,
  "event_id" bigint not null,
  "article_id" bigint not null
);


alter table "public"."event_articles" enable row level security;

CREATE UNIQUE INDEX event_articles_pkey ON public.event_articles USING btree (id);

CREATE INDEX event_articles_event_id_idx ON public.event_articles USING btree (event_id);

alter table "public"."event_articles" add constraint "event_articles_pkey" PRIMARY KEY using index "event_articles_pkey";

alter table "public"."event_articles" add constraint "event_articles_article_id_fkey" FOREIGN KEY (article_id) REFERENCES public.articles(id) not valid;

alter table "public"."event_articles" validate constraint "event_articles_article_id_fkey";

alter table "public"."event_articles" add constraint "event_articles_event_id_fkey" FOREIGN KEY (event_id) REFERENCES public.events(id) not valid;

alter table "public"."event_articles" validate constraint "event_articles_event_id_fkey";


grant select on table "public"."event_articles" to "anon";

grant select on table "public"."event_articles" to "authenticated";

grant select, insert, update, delete on table "public"."event_articles" to "service_role";

grant references on table "public"."event_articles" to "service_role";

grant trigger on table "public"."event_articles" to "service_role";

grant truncate on table "public"."event_articles" to "service_role";


  create policy "Enable read access for all users"
  on "public"."event_articles"
  as permissive
  for select
  to anon, authenticated
using (true);


CREATE OR REPLACE FUNCTION public.get_articles_by_event(
  p_event_id  bigint,
  p_bias_type public.bias_type DEFAULT NULL,
  p_page      int              DEFAULT 1,
  p_size      int              DEFAULT 3,
  p_order     text             DEFAULT 'asc'
)
RETURNS json
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  v_articles    json[];
  v_total_count int;
  v_total_pages int;
BEGIN
  p_page := coalesce(p_page, 1);
  p_size := coalesce(p_size, 3);

  IF p_page < 1 THEN
    RAISE EXCEPTION '페이지는 1 이상이어야 합니다';
  END IF;

  IF p_size < 1 THEN
    RAISE EXCEPTION 'size는 1 이상이어야 합니다';
  END IF;

  IF p_size > 100 THEN
    p_size := 100;
  END IF;

  SELECT COUNT(*)
  INTO v_total_count
  FROM public.event_articles ea
  JOIN public.articles a ON ea.article_id = a.id
  WHERE ea.event_id = p_event_id
    AND (p_bias_type IS NULL OR a.bias_type = p_bias_type);

  v_total_pages := CEIL(v_total_count::numeric / p_size);

  EXECUTE format(
    'SELECT array_agg(row_to_json(a))
     FROM (
       SELECT a.link, a.title, a.summary, a.article_image_url, a.publisher, a.published_at, a.bias_type
       FROM public.event_articles ea
       JOIN public.articles a ON ea.article_id = a.id
       WHERE ea.event_id = $1
         AND ($2::public.bias_type IS NULL OR a.bias_type = $2)
       ORDER BY a.published_at %s
       LIMIT $3 OFFSET $4
     ) a',
    CASE WHEN p_order = 'desc' THEN 'DESC' ELSE 'ASC' END
  )
  INTO v_articles
  USING p_event_id, p_bias_type, p_size, (p_page - 1) * p_size;

  RETURN json_build_object(
    'articles',     coalesce(to_json(v_articles), '[]'::json),
    'page',         p_page,
    'size',         p_size,
    'total_count',  v_total_count,
    'total_pages',  v_total_pages
  );
END;
$$;


GRANT EXECUTE ON FUNCTION "public"."get_articles_by_event"(bigint, public.bias_type, int, int, text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_articles_by_event"(bigint, public.bias_type, int, int, text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_articles_by_event"(bigint, public.bias_type, int, int, text) TO "service_role";


CREATE OR REPLACE FUNCTION public.update_event_counts_on_article_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_bias_type public.bias_type;
BEGIN
  SELECT bias_type INTO v_bias_type
  FROM public.articles
  WHERE id = NEW.article_id;

  UPDATE public.events
  SET
    article_count = article_count + 1,
    left_count  = left_count  + CASE WHEN v_bias_type = 'left'  THEN 1 ELSE 0 END,
    mid_count   = mid_count   + CASE WHEN v_bias_type = 'mid'   THEN 1 ELSE 0 END,
    right_count = right_count + CASE WHEN v_bias_type = 'right' THEN 1 ELSE 0 END
  WHERE id = NEW.event_id;

  RAISE LOG 'update_event_counts_on_article_insert: event_id=%, article_id=%, bias_type=%',
    NEW.event_id, NEW.article_id, v_bias_type;

  RETURN NEW;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.update_event_counts_on_article_insert() FROM PUBLIC;

CREATE TRIGGER update_event_counts_on_article_insert
AFTER INSERT ON public.event_articles
FOR EACH ROW EXECUTE FUNCTION public.update_event_counts_on_article_insert();
