create table "public"."events" (
  "id" bigint generated by default as identity not null,
  "topic_id" bigint not null,
  "category" public.category not null,
  "title" text not null,
  "summary" text not null,
  "article_count" integer not null default 0,
  "left_count" integer not null default 0,
  "mid_count" integer not null default 0,
  "right_count" integer not null default 0,
  "abusing_count" integer not null default 0,
  "event_image_url" text,
  "created_at" timestamp not null default now(),
  "updated_at" timestamp not null default now(),
  "prev_event" bigint,
  "next_event" bigint
);


alter table "public"."events" enable row level security;


create table "public"."topics" (
  "id" bigint generated by default as identity not null,
  "category" public.category not null,
  "title" text not null,
  "summary" text not null,
  "created_at" timestamp not null default now(),
  "updated_at" timestamp not null default now()
);


alter table "public"."topics" enable row level security;


CREATE UNIQUE INDEX events_pkey ON public.events USING btree (id);

CREATE UNIQUE INDEX topics_pkey ON public.topics USING btree (id);

CREATE INDEX events_topic_id_idx ON public.events USING btree (topic_id);

alter table "public"."events" add constraint "events_pkey" PRIMARY KEY using index "events_pkey";

alter table "public"."topics" add constraint "topics_pkey" PRIMARY KEY using index "topics_pkey";

alter table "public"."events" add constraint "events_next_event_fkey" FOREIGN KEY (next_event) REFERENCES public.events(id) not valid;

alter table "public"."events" validate constraint "events_next_event_fkey";

alter table "public"."events" add constraint "events_prev_event_fkey" FOREIGN KEY (prev_event) REFERENCES public.events(id) not valid;

alter table "public"."events" validate constraint "events_prev_event_fkey";

alter table "public"."events" add constraint "events_topic_id_fkey" FOREIGN KEY (topic_id) REFERENCES public.topics(id) not valid;

alter table "public"."events" validate constraint "events_topic_id_fkey";


grant select on table "public"."events" to "anon";

grant select on table "public"."events" to "authenticated";

grant select, insert, update, delete on table "public"."events" to "service_role";

grant references on table "public"."events" to "service_role";

grant trigger on table "public"."events" to "service_role";

grant truncate on table "public"."events" to "service_role";


grant select on table "public"."topics" to "anon";

grant select on table "public"."topics" to "authenticated";

grant select, insert, update, delete on table "public"."topics" to "service_role";

grant references on table "public"."topics" to "service_role";

grant trigger on table "public"."topics" to "service_role";

grant truncate on table "public"."topics" to "service_role";


create policy "Enable read access for all users"
on "public"."events"
as permissive
for select
to anon, authenticated
using (true);


create policy "Enable read access for all users"
on "public"."topics"
as permissive
for select
to anon, authenticated
using (true);


CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.events FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.topics FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();


CREATE OR REPLACE FUNCTION public.get_topic(
  p_topic_id bigint
)
RETURNS json
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
AS $$
DECLARE
  v_topic json;
BEGIN
  SELECT row_to_json(t) INTO v_topic
  FROM (
    SELECT id, category, title, created_at, updated_at
    FROM public.topics
    WHERE id = p_topic_id
  ) t;

  IF v_topic IS NULL THEN
    RAISE EXCEPTION 'topic not found';
  END IF;

  RETURN v_topic;
END;
$$;


CREATE OR REPLACE FUNCTION public.get_events_by_topic(
  p_topic_id  bigint,
  p_cursor_id bigint DEFAULT NULL,
  p_size      int    DEFAULT 3,
  p_order     text   DEFAULT 'asc'
)
RETURNS json
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
AS $$
DECLARE
  v_events      json[];
  v_has_more    boolean := false;
  v_next_cursor bigint;
  v_count       int;
BEGIN
  IF p_size > 100 THEN
    p_size := 100;
  END IF;

  EXECUTE format(
    'SELECT array_agg(row_to_json(e))
     FROM (
       SELECT id, event_image_url, title, summary, created_at, updated_at
       FROM public.events
       WHERE topic_id = $1
         AND ($2::bigint IS NULL OR id %s $2)
       ORDER BY id %s
       LIMIT $3
     ) e',
    CASE WHEN p_order = 'desc' THEN '<=' ELSE '>=' END,
    CASE WHEN p_order = 'desc' THEN 'DESC' ELSE 'ASC' END
  )
  INTO v_events
  USING p_topic_id, p_cursor_id, p_size + 1;

  v_count := coalesce(array_length(v_events, 1), 0);

  IF v_count > p_size THEN
    v_has_more    := true;
    v_next_cursor := (v_events[p_size + 1]->>'id')::bigint;
    v_events      := v_events[1:p_size];
  END IF;

  RETURN json_build_object(
    'events',      coalesce(to_json(v_events), '[]'::json),
    'has_more',    v_has_more,
    'next_cursor', v_next_cursor
  );
END;
$$;


GRANT EXECUTE ON FUNCTION "public"."get_topic"(bigint) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_topic"(bigint) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_topic"(bigint) TO "service_role";

GRANT EXECUTE ON FUNCTION "public"."get_events_by_topic"(bigint, bigint, int, text) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_events_by_topic"(bigint, bigint, int, text) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_events_by_topic"(bigint, bigint, int, text) TO "service_role";


CREATE OR REPLACE FUNCTION public.get_event(
  p_event_id bigint
)
RETURNS json
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
AS $$
DECLARE
  v_event json;
BEGIN
  SELECT row_to_json(e) INTO v_event
  FROM (
    SELECT id, topic_id, category, title, summary,
           article_count, left_count, mid_count, right_count, abusing_count,
           event_image_url, created_at, updated_at, prev_event, next_event
    FROM public.events
    WHERE id = p_event_id
  ) e;

  IF v_event IS NULL THEN
    RAISE EXCEPTION 'event not found';
  END IF;

  RETURN v_event;
END;
$$;


GRANT EXECUTE ON FUNCTION "public"."get_event"(bigint) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_event"(bigint) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_event"(bigint) TO "service_role";
