create table "public"."subscriptions" (
  "id" bigint generated by default as identity not null,
  "user_id" uuid not null,
  "topic_id" bigint not null,
  "created_at" timestamp without time zone not null default now()
);


alter table "public"."subscriptions" enable row level security;

CREATE UNIQUE INDEX subscriptions_pkey ON public.subscriptions USING btree (id);

alter table "public"."subscriptions" add constraint "subscriptions_pkey" PRIMARY KEY using index "subscriptions_pkey";

alter table "public"."subscriptions" add constraint "subscriptions_topic_id_fkey" FOREIGN KEY (topic_id) REFERENCES public.topics(id) not valid;

alter table "public"."subscriptions" validate constraint "subscriptions_topic_id_fkey";

alter table "public"."subscriptions" add constraint "subscriptions_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.profiles(id) not valid;

alter table "public"."subscriptions" validate constraint "subscriptions_user_id_fkey";

CREATE UNIQUE INDEX subscriptions_user_id_topic_id_key
  ON public.subscriptions USING btree (user_id, topic_id);

ALTER TABLE "public"."subscriptions"
  ADD CONSTRAINT "subscriptions_user_id_topic_id_key"
  UNIQUE USING INDEX "subscriptions_user_id_topic_id_key";

grant select, insert, delete on table "public"."subscriptions" to "authenticated";

grant select, insert, update, delete on table "public"."subscriptions" to "service_role";

grant references on table "public"."subscriptions" to "service_role";

grant trigger on table "public"."subscriptions" to "service_role";

grant truncate on table "public"."subscriptions" to "service_role";


create policy "본인 id로만 구독 생성"
on "public"."subscriptions"
as permissive
for insert
to authenticated
with check ((( SELECT auth.uid() AS uid) = user_id));



create policy "본인 구독 정보만 조회"
on "public"."subscriptions"
as permissive
for select
to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));



create policy "본인 구독만 삭제"
on "public"."subscriptions"
as permissive
for delete
to authenticated
using (((SELECT auth.uid()) = user_id));



DROP FUNCTION IF EXISTS public.subscribe_topic(bigint);

CREATE OR REPLACE FUNCTION public.subscribe_topic(p_topic_id bigint)
RETURNS json
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  v_subscription_id bigint;
BEGIN
  IF p_topic_id IS NULL THEN
    RAISE EXCEPTION '토픽 ID는 필수입니다';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.topics WHERE id = p_topic_id) THEN
    RAISE EXCEPTION '존재하지 않는 토픽입니다';
  END IF;

  INSERT INTO public.subscriptions (user_id, topic_id)
  VALUES (auth.uid(), p_topic_id)
  ON CONFLICT ON CONSTRAINT subscriptions_user_id_topic_id_key DO NOTHING
  RETURNING id INTO v_subscription_id;

  IF v_subscription_id IS NULL THEN
    SELECT id
    INTO v_subscription_id
    FROM public.subscriptions
    WHERE user_id = auth.uid()
      AND topic_id = p_topic_id;
  END IF;

  RETURN json_build_object(
    'subscription_id', v_subscription_id,
    'is_subscribed', true
  );
END;
$$;

GRANT EXECUTE ON FUNCTION "public"."subscribe_topic"(bigint) TO "authenticated";



CREATE OR REPLACE FUNCTION public.unsubscribe_topic(p_topic_id bigint)
RETURNS void
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = ''
AS $$
BEGIN
  IF p_topic_id IS NULL THEN
    RAISE EXCEPTION '토픽 ID는 필수입니다';
  END IF;

  DELETE FROM public.subscriptions
  WHERE user_id = auth.uid() AND topic_id = p_topic_id;
END;
$$;

GRANT EXECUTE ON FUNCTION "public"."unsubscribe_topic"(bigint) TO "authenticated";
