create type "public"."abusing_type" as enum ('title_content_mismatch', 'content_context_mismatch');


create table "public"."abusing_articles" (
  "id" bigint generated by default as identity not null,
  "event_id" bigint not null,
  "article_id" bigint not null,
  "type" public.abusing_type not null
);


alter table "public"."abusing_articles" enable row level security;

CREATE UNIQUE INDEX abusing_articles_pkey ON public.abusing_articles USING btree (id);

alter table "public"."abusing_articles" add constraint "abusing_articles_pkey" PRIMARY KEY using index "abusing_articles_pkey";

alter table "public"."abusing_articles" add constraint "abusing_articles_article_id_fkey" FOREIGN KEY (article_id) REFERENCES public.articles(id) not valid;

alter table "public"."abusing_articles" validate constraint "abusing_articles_article_id_fkey";

alter table "public"."abusing_articles" add constraint "abusing_articles_event_id_fkey" FOREIGN KEY (event_id) REFERENCES public.events(id) not valid;

alter table "public"."abusing_articles" validate constraint "abusing_articles_event_id_fkey";


grant select on table "public"."abusing_articles" to "anon";

grant select on table "public"."abusing_articles" to "authenticated";

grant select, insert, update, delete on table "public"."abusing_articles" to "service_role";

grant references on table "public"."abusing_articles" to "service_role";

grant trigger on table "public"."abusing_articles" to "service_role";

grant truncate on table "public"."abusing_articles" to "service_role";


create policy "Enable read access for all users"
on "public"."abusing_articles"
as permissive
for select
to anon, authenticated
using (true);


CREATE OR REPLACE FUNCTION public.increment_abusing_count()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
BEGIN
  UPDATE public.events
  SET abusing_count = abusing_count + 1
  WHERE id = NEW.event_id;

  RAISE LOG 'increment_abusing_count: event_id=%, article_id=%, type=%',
    NEW.event_id, NEW.article_id, NEW.type;

  RETURN NEW;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.increment_abusing_count() FROM PUBLIC;

CREATE TRIGGER increment_abusing_count
AFTER INSERT ON public.abusing_articles
FOR EACH ROW EXECUTE FUNCTION public.increment_abusing_count();


CREATE OR REPLACE FUNCTION public.decrement_bias_count()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ''
AS $$
DECLARE
  v_bias_type public.bias_type;
BEGIN
  SELECT bias_type INTO v_bias_type
  FROM public.articles
  WHERE id = NEW.article_id;

  UPDATE public.events
  SET
    left_count  = CASE WHEN v_bias_type = '진보' THEN left_count  - 1 ELSE left_count  END,
    mid_count   = CASE WHEN v_bias_type = '중도' THEN mid_count   - 1 ELSE mid_count   END,
    right_count = CASE WHEN v_bias_type = '보수' THEN right_count - 1 ELSE right_count END
  WHERE id = NEW.event_id;

  RAISE LOG 'decrement_bias_count: event_id=%, article_id=%, bias_type=%',
    NEW.event_id, NEW.article_id, v_bias_type;

  RETURN NEW;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.decrement_bias_count() FROM PUBLIC;

CREATE TRIGGER decrement_bias_count
AFTER INSERT ON public.abusing_articles
FOR EACH ROW EXECUTE FUNCTION public.decrement_bias_count();


CREATE OR REPLACE FUNCTION public.get_abusing_articles_by_event(
  p_event_id     bigint,
  p_abusing_type public.abusing_type DEFAULT NULL,
  p_page         int                 DEFAULT 1,
  p_size         int                 DEFAULT 4
)
RETURNS json
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
SET search_path = ''
AS $$
DECLARE
  v_articles    json[];
  v_total_count int;
  v_total_pages int;
BEGIN
  p_page := coalesce(p_page, 1);
  p_size := coalesce(p_size, 4);

  IF p_page < 1 THEN
    RAISE EXCEPTION 'page는 1 이상이어야 합니다';
  END IF;

  IF p_size < 1 THEN
    RAISE EXCEPTION 'size는 1 이상이어야 합니다';
  END IF;

  IF p_size > 100 THEN
    p_size := 100;
  END IF;

  SELECT COUNT(*)
  INTO v_total_count
  FROM public.abusing_articles aa
  WHERE aa.event_id = p_event_id
    AND (p_abusing_type IS NULL OR aa.type = p_abusing_type);

  v_total_pages := CEIL(v_total_count::numeric / p_size);

  SELECT array_agg(row_to_json(r))
  INTO v_articles
  FROM (
    SELECT a.link, a.title, a.summary, a.article_image_url, a.publisher, a.published_at
    FROM public.abusing_articles aa
    JOIN public.articles a ON aa.article_id = a.id
    WHERE aa.event_id = p_event_id
      AND (p_abusing_type IS NULL OR aa.type = p_abusing_type)
    ORDER BY aa.id DESC
    LIMIT p_size OFFSET (p_page - 1) * p_size
  ) r;

  RETURN json_build_object(
    'articles',    coalesce(to_json(v_articles), '[]'::json),
    'page',        p_page,
    'size',        p_size,
    'total_count', v_total_count,
    'total_pages', v_total_pages
  );
END;
$$;


GRANT EXECUTE ON FUNCTION "public"."get_abusing_articles_by_event"(bigint, public.abusing_type, int, int) TO "anon";
GRANT EXECUTE ON FUNCTION "public"."get_abusing_articles_by_event"(bigint, public.abusing_type, int, int) TO "authenticated";
GRANT EXECUTE ON FUNCTION "public"."get_abusing_articles_by_event"(bigint, public.abusing_type, int, int) TO "service_role";



