-- =============================================================
-- Subtopic 기능 스키마 추가
-- - events: Subtopic 마지막 처리 시각 추가
-- - event_profiles: Subtopic 분류 전용 Event Profile 저장
-- - subtopics: Topic 내부 Subtopic 저장
-- - subtopic_events: Event <-> Subtopic N:M 관계 저장
-- =============================================================


-- -------------------------------------------------------------
-- 1. events: Subtopic 마지막 처리 시각
--    NULL이면 아직 Subtopic 분류 파이프라인에서 처리되지 않은 Event
-- -------------------------------------------------------------
ALTER TABLE public.events
  ADD COLUMN subtopic_processed_at timestamp without time zone;


-- -------------------------------------------------------------
-- 2. event_profiles
--    기존 events.summary와 별개인 Subtopic 분류 전용 Profile
-- -------------------------------------------------------------
CREATE TABLE public.event_profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  event_id bigint NOT NULL,
  event_summary text NOT NULL,
  anchors jsonb NOT NULL,
  input_hash text,
  prompt_version text,
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now()
);

ALTER TABLE public.event_profiles ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX event_profiles_pkey
  ON public.event_profiles USING btree (id);

CREATE UNIQUE INDEX event_profiles_event_id_key
  ON public.event_profiles USING btree (event_id);

ALTER TABLE public.event_profiles
  ADD CONSTRAINT event_profiles_pkey
  PRIMARY KEY USING INDEX event_profiles_pkey;

ALTER TABLE public.event_profiles
  ADD CONSTRAINT event_profiles_event_id_key
  UNIQUE USING INDEX event_profiles_event_id_key;

ALTER TABLE public.event_profiles
  ADD CONSTRAINT event_profiles_event_id_fkey
  FOREIGN KEY (event_id)
  REFERENCES public.events(id)
  ON DELETE CASCADE
  NOT VALID;

ALTER TABLE public.event_profiles
  VALIDATE CONSTRAINT event_profiles_event_id_fkey;

-- 내부 AI 처리용 테이블: anon/authenticated에는 직접 접근 권한을 주지 않는다.
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.event_profiles TO service_role;
GRANT REFERENCES ON TABLE public.event_profiles TO service_role;
GRANT TRIGGER ON TABLE public.event_profiles TO service_role;
GRANT TRUNCATE ON TABLE public.event_profiles TO service_role;

CREATE TRIGGER set_updated_at
BEFORE UPDATE ON public.event_profiles
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at();


-- -------------------------------------------------------------
-- 3. subtopics
--    common_basis: Event들이 같은 Subtopic으로 묶인 공통 기준
--    membership_criterion: 신규 Event의 기존 Subtopic 귀속 판단 기준
--    summary: 사용자 표시용 요약 (별도 생성, nullable)
-- -------------------------------------------------------------
CREATE TABLE public.subtopics (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  topic_id bigint NOT NULL,
  name text NOT NULL,
  common_basis text,
  membership_criterion text,
  summary text,
  type text NOT NULL,
  CONSTRAINT subtopics_type_check CHECK (type IN ('FOCAL_POINT', 'PROCESS', 'RECURRING_ISSUE')),
  created_at timestamp without time zone NOT NULL DEFAULT now(),
  updated_at timestamp without time zone NOT NULL DEFAULT now()
);

ALTER TABLE public.subtopics ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX subtopics_pkey
  ON public.subtopics USING btree (id);

CREATE INDEX subtopics_topic_id_idx
  ON public.subtopics USING btree (topic_id);

ALTER TABLE public.subtopics
  ADD CONSTRAINT subtopics_pkey
  PRIMARY KEY USING INDEX subtopics_pkey;

ALTER TABLE public.subtopics
  ADD CONSTRAINT subtopics_topic_id_fkey
  FOREIGN KEY (topic_id)
  REFERENCES public.topics(id)
  ON DELETE CASCADE
  NOT VALID;

ALTER TABLE public.subtopics
  VALIDATE CONSTRAINT subtopics_topic_id_fkey;

GRANT SELECT ON TABLE public.subtopics TO anon;
GRANT SELECT ON TABLE public.subtopics TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.subtopics TO service_role;
GRANT REFERENCES ON TABLE public.subtopics TO service_role;
GRANT TRIGGER ON TABLE public.subtopics TO service_role;
GRANT TRUNCATE ON TABLE public.subtopics TO service_role;

CREATE POLICY "Enable read access for all users"
ON public.subtopics
AS PERMISSIVE
FOR SELECT
TO anon, authenticated
USING (true);

CREATE TRIGGER set_updated_at
BEFORE UPDATE ON public.subtopics
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at();


-- -------------------------------------------------------------
-- 4. subtopic_events
--    하나의 Event가 여러 Subtopic에 속할 수 있으므로 N:M 관계로 관리
-- -------------------------------------------------------------
CREATE TABLE public.subtopic_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  subtopic_id bigint NOT NULL,
  event_id bigint NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT now()
);

ALTER TABLE public.subtopic_events ENABLE ROW LEVEL SECURITY;

CREATE UNIQUE INDEX subtopic_events_pkey
  ON public.subtopic_events USING btree (id);

-- 동일 Event가 동일 Subtopic에 중복 연결되는 것을 방지한다.
-- 선행 컬럼이 subtopic_id이므로 Subtopic별 Event 조회도 이 인덱스로 커버한다.
CREATE UNIQUE INDEX subtopic_events_subtopic_id_event_id_key
  ON public.subtopic_events USING btree (subtopic_id, event_id);

-- Event 기준으로 연결된 Subtopic을 조회할 때 사용한다.
CREATE INDEX subtopic_events_event_id_idx
  ON public.subtopic_events USING btree (event_id);

ALTER TABLE public.subtopic_events
  ADD CONSTRAINT subtopic_events_pkey
  PRIMARY KEY USING INDEX subtopic_events_pkey;

ALTER TABLE public.subtopic_events
  ADD CONSTRAINT subtopic_events_subtopic_id_event_id_key
  UNIQUE USING INDEX subtopic_events_subtopic_id_event_id_key;

ALTER TABLE public.subtopic_events
  ADD CONSTRAINT subtopic_events_subtopic_id_fkey
  FOREIGN KEY (subtopic_id)
  REFERENCES public.subtopics(id)
  ON DELETE CASCADE
  NOT VALID;

ALTER TABLE public.subtopic_events
  VALIDATE CONSTRAINT subtopic_events_subtopic_id_fkey;

ALTER TABLE public.subtopic_events
  ADD CONSTRAINT subtopic_events_event_id_fkey
  FOREIGN KEY (event_id)
  REFERENCES public.events(id)
  ON DELETE CASCADE
  NOT VALID;

ALTER TABLE public.subtopic_events
  VALIDATE CONSTRAINT subtopic_events_event_id_fkey;

-- Subtopic과 Event는 반드시 동일한 Topic에 속해야 한다.
-- FK는 각 행의 존재 여부만 보장하므로, 교차 Topic 연결은 별도 트리거로 방지한다.
CREATE OR REPLACE FUNCTION public.validate_subtopic_event_same_topic()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = ''
AS $$
DECLARE
  v_subtopic_topic_id bigint;
  v_event_topic_id bigint;
BEGIN
  SELECT s.topic_id, e.topic_id
  INTO v_subtopic_topic_id, v_event_topic_id
  FROM public.subtopics AS s
  CROSS JOIN public.events AS e
  WHERE s.id = NEW.subtopic_id
    AND e.id = NEW.event_id;

  -- 존재하지 않는 FK 값은 기존 FK 제약이 처리하도록 둔다.
  IF NOT FOUND THEN
    RETURN NEW;
  END IF;

  IF v_subtopic_topic_id IS DISTINCT FROM v_event_topic_id THEN
    RAISE EXCEPTION USING
      ERRCODE = '23514',
      MESSAGE = 'subtopic_events topic mismatch: subtopic and event must belong to the same topic';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER enforce_subtopic_event_same_topic
BEFORE INSERT OR UPDATE OF subtopic_id, event_id
ON public.subtopic_events
FOR EACH ROW
EXECUTE FUNCTION public.validate_subtopic_event_same_topic();

GRANT SELECT ON TABLE public.subtopic_events TO anon;
GRANT SELECT ON TABLE public.subtopic_events TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.subtopic_events TO service_role;
GRANT REFERENCES ON TABLE public.subtopic_events TO service_role;
GRANT TRIGGER ON TABLE public.subtopic_events TO service_role;
GRANT TRUNCATE ON TABLE public.subtopic_events TO service_role;

CREATE POLICY "Enable read access for all users"
ON public.subtopic_events
AS PERMISSIVE
FOR SELECT
TO anon, authenticated
USING (true);
