CREATE EXTENSION IF NOT EXISTS vector SCHEMA "extensions";

-- 기사 (제목 + 첫 문단) 임베딩
ALTER TABLE "public"."articles"
  ADD COLUMN embedding "extensions".vector(768);

-- 이벤트 (제목 + 요약문) 임베딩
ALTER TABLE "public"."events"
  ADD COLUMN embedding "extensions".vector(768);

-- 토픽 분류 전 이벤트 허용: (article_count - abusing_count) >= n 조건으로 서버에서 판단
ALTER TABLE "public"."events"
  ALTER COLUMN topic_id DROP NOT NULL;

-- 토픽별 원인 문장 및 임베딩 저장
CREATE TABLE "public"."topic_causes" (
  id              bigint generated by default as identity primary key,
  topic_id        bigint not null references "public"."topics"(id),
  cause_text      text not null,
  cause_embedding "extensions".vector(768)
);

CREATE INDEX topic_causes_topic_id_idx ON public.topic_causes USING btree (topic_id);

ALTER TABLE "public"."topic_causes" ENABLE ROW LEVEL SECURITY;

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."topic_causes" TO "service_role";
