create type "public"."article_status" as enum ('needs_crawl', 'ready', 'crawl_failed');

create type "public"."bias_type" as enum ('left', 'mid', 'right');

create type "public"."category" as enum ('정치', '경제', '사회');

create type "public"."content_source" as enum ('rss', 'crawl');


create table "public"."articles" (
  "id" bigint generated by default as identity not null,
  "feed_url" text not null,
  "guid" bigint not null,
  "link" text not null,
  "category" public.category not null,
  "title" text not null,
  "summary" text not null,
  "content" text,
  "content_source" public.content_source not null,
  "publisher" text not null,
  "published_at" timestamp not null,
  "bias_type" public.bias_type not null,
  "status" public.article_status not null,
  "article_image_url" text,
  "created_at" timestamp not null default now(),
  "updated_at" timestamp not null default now()
);


alter table "public"."articles" enable row level security;

CREATE UNIQUE INDEX articles_pkey ON public.articles USING btree (id);

alter table "public"."articles" add constraint "articles_pkey" PRIMARY KEY using index "articles_pkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.update_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

grant select on table "public"."articles" to "anon";

grant select on table "public"."articles" to "authenticated";

grant select, insert, update, delete on table "public"."articles" to "service_role";

grant references on table "public"."articles" to "service_role";

grant trigger on table "public"."articles" to "service_role";

grant truncate on table "public"."articles" to "service_role";


create policy "Enable read access for all users"
on "public"."articles"
as permissive
for select
to anon, authenticated
using (true);


CREATE TRIGGER set_updated_at BEFORE UPDATE ON public.articles FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();
