create type "public"."article_job_status" as enum (
  'pending',
  'sent',
  'failed'
);


create table "public"."article_jobs" (
  "id" bigint generated by default as identity not null,
  "article_id" bigint not null,
  "status" public.article_job_status not null default 'pending',
  "attempts" integer not null default 0,
  "last_error" text,
  "last_attempt_at" timestamp,
  "created_at" timestamp not null default now(),
  "updated_at" timestamp not null default now()
);


alter table "public"."article_jobs" enable row level security;


-- PK
CREATE UNIQUE INDEX article_jobs_pkey ON public.article_jobs USING btree (id);

alter table "public"."article_jobs"
  add constraint "article_jobs_pkey"
  PRIMARY KEY using index "article_jobs_pkey";


alter table "public"."article_jobs"
  add constraint "article_jobs_article_id_fkey"
  FOREIGN KEY (article_id)
  REFERENCES public.articles(id)
  ON DELETE CASCADE
  not valid;

alter table "public"."article_jobs"
  validate constraint "article_jobs_article_id_fkey";


CREATE TRIGGER set_updated_at
BEFORE UPDATE ON public.article_jobs
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at();

grant select, insert, update, delete on table "public"."article_jobs" to "service_role";
grant references on table "public"."article_jobs" to "service_role";
grant trigger on table "public"."article_jobs" to "service_role";

grant truncate on table "public"."article_jobs" to "service_role";